import React from 'react';
import { ShoppingCart, Coffee, Car, Home, Zap, HeartPulse, Gamepad2, Plane, ShoppingBag, GraduationCap, Gift, TrendingUp } from 'lucide-react';
import { Account, Currency } from './types';

export const INITIAL_RATE = 50.50;

export const MOCK_ACCOUNTS: Account[] = [];

export const CATEGORIES = [
  { id: 'food', name: 'cat_food', icon: <ShoppingCart size={20} />, color: 'bg-orange-500/20 text-orange-400' },
  { id: 'transport', name: 'cat_transport', icon: <Car size={20} />, color: 'bg-blue-500/20 text-blue-400' },
  { id: 'coffee', name: 'cat_coffee', icon: <Coffee size={20} />, color: 'bg-amber-700/20 text-amber-500' },
  { id: 'home', name: 'cat_home', icon: <Home size={20} />, color: 'bg-indigo-500/20 text-indigo-400' },
  { id: 'bills', name: 'cat_bills', icon: <Zap size={20} />, color: 'bg-yellow-500/20 text-yellow-400' },
  { id: 'health', name: 'cat_health', icon: <HeartPulse size={20} />, color: 'bg-red-500/20 text-red-400' },
  { id: 'entertainment', name: 'cat_entertainment', icon: <Gamepad2 size={20} />, color: 'bg-purple-500/20 text-purple-400' },
  { id: 'travel', name: 'cat_travel', icon: <Plane size={20} />, color: 'bg-sky-500/20 text-sky-400' },
  { id: 'shopping', name: 'cat_shopping', icon: <ShoppingBag size={20} />, color: 'bg-pink-500/20 text-pink-400' },
  { id: 'education', name: 'cat_education', icon: <GraduationCap size={20} />, color: 'bg-emerald-500/20 text-emerald-400' },
  { id: 'gift', name: 'cat_gift', icon: <Gift size={20} />, color: 'bg-rose-500/20 text-rose-400' },
  { id: 'investment', name: 'cat_investment', icon: <TrendingUp size={20} />, color: 'bg-green-500/20 text-green-400' },
];

export const SMART_CATEGORIES: Record<string, string> = {
  'uber': 'transport',
  'taxi': 'transport',
  'bus': 'transport',
  'lyft': 'transport',
  'train': 'transport',
  'fuel': 'transport',
  'gas': 'transport',
  'starbucks': 'coffee',
  'cafe': 'coffee',
  'latte': 'coffee',
  'netflix': 'entertainment',
  'spotify': 'entertainment',
  'hulu': 'entertainment',
  'cinema': 'entertainment',
  'game': 'entertainment',
  'steam': 'entertainment',
  'gym': 'health',
  'doctor': 'health',
  'pharmacy': 'health',
  'medication': 'health',
  'hospital': 'health',
  'market': 'food',
  'walmart': 'food',
  'dinner': 'food',
  'lunch': 'food',
  'restaurant': 'food',
  'grocery': 'food',
  'burger': 'food',
  'pizza': 'food',
  'amazon': 'shopping',
  'nike': 'shopping',
  'zara': 'shopping',
  'clothes': 'shopping',
  'shoes': 'shopping',
  'udemy': 'education',
  'course': 'education',
  'tuition': 'education',
  'book': 'education',
  'school': 'education',
  'rent': 'home',
  'internet': 'bills',
  'electric': 'bills',
  'water': 'bills',
  'phone': 'bills',
  'flight': 'travel',
  'hotel': 'travel',
  'airbnb': 'travel',
  'birthday': 'gift',
  'present': 'gift',
  'donation': 'gift',
  'bitcoin': 'investment',
  'stock': 'investment',
  'crypto': 'investment',
  'save': 'investment',
};