import React from 'react';
import { ShoppingCart, Coffee, Car, Home, Zap, HeartPulse, Gamepad2, Plane, ShoppingBag, GraduationCap, Gift, TrendingUp, PawPrint, Baby, Umbrella, FileText, Palmtree, Smartphone, Globe, Briefcase, User, Search, Smile, Music, Film, Tv, Monitor, DollarSign, MoreHorizontal } from 'lucide-react';
import { Account, Currency } from './types';

export const INITIAL_RATE = 50.50;

export const MOCK_ACCOUNTS: Account[] = [];

export const CATEGORIES = [
  { id: 'food', name: 'cat_food', icon: <ShoppingCart size={20} />, color: 'bg-orange-500/20 text-orange-400' },
  { id: 'transport', name: 'cat_transport', icon: <Car size={20} />, color: 'bg-blue-500/20 text-blue-400' },
  { id: 'coffee', name: 'cat_coffee', icon: <Coffee size={20} />, color: 'bg-amber-700/20 text-amber-500' },
  { id: 'home', name: 'cat_home', icon: <Home size={20} />, color: 'bg-indigo-500/20 text-indigo-400' },
  { id: 'bills', name: 'cat_bills', icon: <Zap size={20} />, color: 'bg-yellow-500/20 text-yellow-400' },
  { id: 'health', name: 'cat_health', icon: <HeartPulse size={20} />, color: 'bg-red-500/20 text-red-400' },
  { id: 'entertainment', name: 'cat_entertainment', icon: <Gamepad2 size={20} />, color: 'bg-purple-500/20 text-purple-400' },
  { id: 'travel', name: 'cat_travel', icon: <Plane size={20} />, color: 'bg-sky-500/20 text-sky-400' },
  { id: 'shopping', name: 'cat_shopping', icon: <ShoppingBag size={20} />, color: 'bg-pink-500/20 text-pink-400' },
  { id: 'education', name: 'cat_education', icon: <GraduationCap size={20} />, color: 'bg-emerald-500/20 text-emerald-400' },
  { id: 'gift', name: 'cat_gift', icon: <Gift size={20} />, color: 'bg-rose-500/20 text-rose-400' },
  { id: 'investment', name: 'cat_investment', icon: <TrendingUp size={20} />, color: 'bg-green-500/20 text-green-400' },
  { id: 'pets', name: 'cat_pets', icon: <PawPrint size={20} />, color: 'bg-amber-500/20 text-amber-400' },
  { id: 'kids', name: 'cat_kids', icon: <Baby size={20} />, color: 'bg-blue-300/20 text-blue-300' },
  { id: 'insurance', name: 'cat_insurance', icon: <Umbrella size={20} />, color: 'bg-indigo-700/20 text-indigo-400' },
  { id: 'taxes', name: 'cat_taxes', icon: <FileText size={20} />, color: 'bg-gray-500/20 text-gray-400' },
  { id: 'vacation', name: 'cat_vacation', icon: <Palmtree size={20} />, color: 'bg-cyan-500/20 text-cyan-400' },
  { id: 'electronics', name: 'cat_electronics', icon: <Smartphone size={20} />, color: 'bg-zinc-500/20 text-zinc-300' },
  { id: 'subscription', name: 'cat_subscription', icon: <Globe size={20} />, color: 'bg-violet-500/20 text-violet-400' },
  { id: 'services', name: 'cat_services', icon: <Briefcase size={20} />, color: 'bg-slate-500/20 text-slate-400' },
  { id: 'personal', name: 'cat_personal', icon: <User size={20} />, color: 'bg-teal-500/20 text-teal-400' },
  { id: 'charity', name: 'cat_charity', icon: <HeartPulse size={20} />, color: 'bg-rose-300/20 text-rose-300' },
  { id: 'income', name: 'cat_income', icon: <DollarSign size={20} />, color: 'bg-emerald-600/20 text-emerald-400' },
  { id: 'work', name: 'cat_work', icon: <Briefcase size={20} />, color: 'bg-slate-600/20 text-slate-300' },
  { id: 'freelance', name: 'cat_freelance', icon: <Globe size={20} />, color: 'bg-indigo-400/20 text-indigo-300' },
  { id: 'business', name: 'cat_business', icon: <Briefcase size={20} />, color: 'bg-blue-600/20 text-blue-400' },
  { id: 'other', name: 'cat_other', icon: <MoreHorizontal size={20} />, color: 'bg-gray-600/20 text-gray-300' },
];

export const SMART_CATEGORIES: Record<string, string> = {
  'uber': 'transport',
  'taxi': 'transport',
  'bus': 'transport',
  'lyft': 'transport',
  'train': 'transport',
  'fuel': 'transport',
  'gas': 'transport',
  'starbucks': 'coffee',
  'cafe': 'coffee',
  'latte': 'coffee',
  'netflix': 'entertainment',
  'spotify': 'entertainment',
  'hulu': 'entertainment',
  'cinema': 'entertainment',
  'game': 'entertainment',
  'steam': 'entertainment',
  'gym': 'health',
  'doctor': 'health',
  'pharmacy': 'health',
  'medication': 'health',
  'hospital': 'health',
  'market': 'food',
  'walmart': 'food',
  'dinner': 'food',
  'lunch': 'food',
  'restaurant': 'food',
  'grocery': 'food',
  'burger': 'food',
  'pizza': 'food',
  'amazon': 'shopping',
  'nike': 'shopping',
  'zara': 'shopping',
  'clothes': 'shopping',
  'shoes': 'shopping',
  'udemy': 'education',
  'course': 'education',
  'tuition': 'education',
  'book': 'education',
  'school': 'education',
  'rent': 'home',
  'internet': 'bills',
  'electric': 'bills',
  'water': 'bills',
  'phone': 'bills',
  'flight': 'travel',
  'hotel': 'travel',
  'airbnb': 'travel',
  'birthday': 'gift',
  'present': 'gift',
  'donation': 'gift',
  'bitcoin': 'investment',
  'stock': 'investment',
  'crypto': 'investment',
  'save': 'investment',
  'save': 'investment',
  'vet': 'pets',
  'dog': 'pets',
  'cat': 'pets',
  'pet food': 'pets',
  'grooming': 'pets',
  'baby': 'kids',
  'diapers': 'kids',
  'daycare': 'kids',
  'tuition': 'kids',
  'toys': 'kids',
  'insurance': 'insurance',
  'policy': 'insurance',
  'health insurance': 'insurance',
  'car insurance': 'insurance',
  'life insurance': 'insurance',
  'tax': 'taxes',
  'irs': 'taxes',
  'audit': 'taxes',
  'property tax': 'taxes',
  'income tax': 'taxes',
  'hotel': 'vacation',
  'airbnb': 'vacation',
  'flight': 'vacation',
  'resort': 'vacation',
  'tour': 'vacation',
  'iphone': 'electronics',
  'samsung': 'electronics',
  'laptop': 'electronics',
  'computer': 'electronics',
  'camera': 'electronics',
  'netflix': 'subscription',
  'spotify': 'subscription',
  'youtube': 'subscription',
  'hulu': 'subscription',
  'prime': 'subscription',
  'cleaning': 'services',
  'repair': 'services',
  'laundry': 'services',
  'mechanic': 'services',
  'plumber': 'services',
  'haircut': 'personal',
  'salon': 'personal',
  'spa': 'personal',
  'makeup': 'personal',
  'massage': 'personal',
  'donation': 'charity',
  'charity': 'charity',
  'ngo': 'charity',
  'fundraiser': 'charity',
  'church': 'charity',
  'software': 'electronics',
  'app': 'electronics',
  'internet': 'bills',
  'wifi': 'bills',
  'data': 'bills',
  'phone': 'bills',
  'mobile': 'bills',
  'concert': 'entertainment',
  'movie': 'entertainment',
  'ticket': 'entertainment',
  'museum': 'entertainment',
  'park': 'entertainment',
  'taxi': 'transport',
  'uber': 'transport',
  'lyft': 'transport',
  'bus': 'transport',
  'train': 'transport',
  'fuel': 'transport',
  'gas': 'transport',
  'parking': 'transport',
  'toll': 'transport',
  'groceries': 'food',
  'supermarket': 'food',
  'market': 'food',
  'snacks': 'food',
  'drinks': 'food',
  'bar': 'entertainment',
  'pub': 'entertainment',
  'club': 'entertainment',
  'salary': 'income',
  'paycheck': 'income',
  'wages': 'income',
  'bonus': 'income',
  'deposit': 'income',
  'payroll': 'work',
  'client': 'freelance',
  'project': 'freelance',
  'upwork': 'freelance',
  'fiverr': 'freelance',
  'contract': 'freelance',
  'sales': 'business',
  'revenue': 'business',
  'profit': 'business',
  'atm': 'bills', 
  'cash': 'bills', 
  'withdrawal': 'bills',
  'fee': 'bills',
  'misc': 'other',
  'general': 'other',
  'stuff': 'other',
  'unknown': 'other',
  'lunch': 'food',
  'breakfast': 'food',
  'brunch': 'food',
  'bistro': 'food',
  'bakery': 'food',
  'diner': 'food',
  'takeout': 'food',
  'delivery': 'food',
  'subway': 'transport', 
  'metro': 'transport',
  'cab': 'transport',
  'flight': 'travel',
  'ticket': 'travel', 
  'booking': 'travel',
  'pharmacy': 'health',
  'drugstore': 'health',
  'checkup': 'health',
  'dentist': 'health',
  'vision': 'health',
  'glasses': 'health',
};