import React from 'react';
import { ShoppingCart, Coffee, Car, Home, Zap, HeartPulse, Gamepad2, Plane, ShoppingBag, GraduationCap, Gift, TrendingUp, PawPrint, Baby, Umbrella, FileText, Palmtree, Smartphone, Globe, Briefcase, User, Search, Smile, Music, Film, Tv, Monitor, DollarSign, MoreHorizontal } from 'lucide-react';
import { Account, Currency } from './types';

export const INITIAL_RATE = 50.50;

export const MOCK_ACCOUNTS: Account[] = [];

export const CATEGORIES = [
  { id: 'food', name: 'cat_food', icon: <ShoppingCart size={20} />, color: 'bg-orange-500/20 text-orange-400' },
  { id: 'transport', name: 'cat_transport', icon: <Car size={20} />, color: 'bg-blue-500/20 text-blue-400' },
  { id: 'coffee', name: 'cat_coffee', icon: <Coffee size={20} />, color: 'bg-amber-700/20 text-amber-500' },
  { id: 'home', name: 'cat_home', icon: <Home size={20} />, color: 'bg-indigo-500/20 text-indigo-400' },
  { id: 'bills', name: 'cat_bills', icon: <Zap size={20} />, color: 'bg-yellow-500/20 text-yellow-400' },
  { id: 'health', name: 'cat_health', icon: <HeartPulse size={20} />, color: 'bg-red-500/20 text-red-400' },
  { id: 'entertainment', name: 'cat_entertainment', icon: <Gamepad2 size={20} />, color: 'bg-purple-500/20 text-purple-400' },
  { id: 'travel', name: 'cat_travel', icon: <Plane size={20} />, color: 'bg-sky-500/20 text-sky-400' },
  { id: 'shopping', name: 'cat_shopping', icon: <ShoppingBag size={20} />, color: 'bg-pink-500/20 text-pink-400' },
  { id: 'education', name: 'cat_education', icon: <GraduationCap size={20} />, color: 'bg-emerald-500/20 text-emerald-400' },
  { id: 'gift', name: 'cat_gift', icon: <Gift size={20} />, color: 'bg-rose-500/20 text-rose-400' },
  { id: 'investment', name: 'cat_investment', icon: <TrendingUp size={20} />, color: 'bg-green-500/20 text-green-400' },
  { id: 'pets', name: 'cat_pets', icon: <PawPrint size={20} />, color: 'bg-amber-500/20 text-amber-400' },
  { id: 'kids', name: 'cat_kids', icon: <Baby size={20} />, color: 'bg-blue-300/20 text-blue-300' },
  { id: 'insurance', name: 'cat_insurance', icon: <Umbrella size={20} />, color: 'bg-indigo-700/20 text-indigo-400' },
  { id: 'taxes', name: 'cat_taxes', icon: <FileText size={20} />, color: 'bg-gray-500/20 text-gray-400' },
  { id: 'vacation', name: 'cat_vacation', icon: <Palmtree size={20} />, color: 'bg-cyan-500/20 text-cyan-400' },
  { id: 'electronics', name: 'cat_electronics', icon: <Smartphone size={20} />, color: 'bg-zinc-500/20 text-zinc-300' },
  { id: 'subscription', name: 'cat_subscription', icon: <Globe size={20} />, color: 'bg-violet-500/20 text-violet-400' },
  { id: 'services', name: 'cat_services', icon: <Briefcase size={20} />, color: 'bg-slate-500/20 text-slate-400' },
  { id: 'personal', name: 'cat_personal', icon: <User size={20} />, color: 'bg-teal-500/20 text-teal-400' },
  { id: 'charity', name: 'cat_charity', icon: <HeartPulse size={20} />, color: 'bg-rose-300/20 text-rose-300' },
  { id: 'income', name: 'cat_income', icon: <DollarSign size={20} />, color: 'bg-emerald-600/20 text-emerald-400' },
  { id: 'work', name: 'cat_work', icon: <Briefcase size={20} />, color: 'bg-slate-600/20 text-slate-300' },
  { id: 'freelance', name: 'cat_freelance', icon: <Globe size={20} />, color: 'bg-indigo-400/20 text-indigo-300' },
  { id: 'business', name: 'cat_business', icon: <Briefcase size={20} />, color: 'bg-blue-600/20 text-blue-400' },
  { id: 'other', name: 'cat_other', icon: <MoreHorizontal size={20} />, color: 'bg-gray-600/20 text-gray-300' },
];

const SHARED_CATEGORIES: Record<string, string> = {
  'uber': 'transport',
  'taxi': 'transport',
  'bus': 'transport',
  'lyft': 'transport',
  'train': 'transport',
  'netflix': 'subscription',
  'spotify': 'subscription',
  'hulu': 'subscription',
  'youtube': 'subscription',
  'prime': 'subscription',
  'hbo': 'subscription',
  'disney': 'subscription',
  'starbucks': 'coffee',
  'amazon': 'shopping',
  'nike': 'shopping',
  'zara': 'shopping',
  'udemy': 'education',
  'steam': 'entertainment',
  'upwork': 'freelance',
  'fiverr': 'freelance',
  'airbnb': 'travel',
  'booking': 'travel',
  'bitcoin': 'investment',
  'iphone': 'electronics',
  'samsung': 'electronics',
};

export const SMART_CATEGORIES_EN: Record<string, string> = {
  ...SHARED_CATEGORIES,
  'fuel': 'transport',
  'gas': 'transport',
  'coffee': 'coffee',
  'cafe': 'coffee',
  'latte': 'coffee',
  'cinema': 'entertainment',
  'game': 'entertainment',
  'movie': 'entertainment',
  'concert': 'entertainment',
  'museum': 'entertainment',
  'park': 'entertainment',
  'bar': 'entertainment',
  'pub': 'entertainment',
  'club': 'entertainment',
  'gym': 'health',
  'doctor': 'health',
  'pharmacy': 'health',
  'medication': 'health',
  'hospital': 'health',
  'drugstore': 'health',
  'checkup': 'health',
  'dentist': 'health',
  'vision': 'health',
  'glasses': 'health',
  'market': 'food',
  'supermarket': 'food',
  'walmart': 'food',
  'dinner': 'food',
  'lunch': 'food',
  'restaurant': 'food',
  'grocery': 'food',
  'burger': 'food',
  'pizza': 'food',
  'breakfast': 'food',
  'brunch': 'food',
  'bistro': 'food',
  'bakery': 'food',
  'diner': 'food',
  'takeout': 'food',
  'delivery': 'food',
  'snacks': 'food',
  'drinks': 'food',
  'clothes': 'shopping',
  'shoes': 'shopping',
  'course': 'education',
  'tuition': 'education',
  'book': 'education',
  'school': 'education',
  'university': 'education',
  'rent': 'home',
  'mortgage': 'home',
  'internet': 'bills',
  'electric': 'bills',
  'water': 'bills',
  'phone': 'bills',
  'wifi': 'bills',
  'data': 'bills',
  'mobile': 'bills',
  'flight': 'travel',
  'hotel': 'travel',
  'ticket': 'travel',
  'birthday': 'gift',
  'present': 'gift',
  'donation': 'charity',
  'ngo': 'charity',
  'fundraiser': 'charity',
  'church': 'charity',
  'stock': 'investment',
  'crypto': 'investment',
  'save': 'investment',
  'invest': 'investment',
  'vet': 'pets',
  'dog': 'pets',
  'cat': 'pets',
  'pet food': 'pets',
  'grooming': 'pets',
  'baby': 'kids',
  'diapers': 'kids',
  'daycare': 'kids',
  'toys': 'kids',
  'insurance': 'insurance',
  'policy': 'insurance',
  'health insurance': 'insurance',
  'car insurance': 'insurance',
  'life insurance': 'insurance',
  'tax': 'taxes',
  'irs': 'taxes',
  'audit': 'taxes',
  'property tax': 'taxes',
  'income tax': 'taxes',
  'resort': 'vacation',
  'tour': 'vacation',
  'beach': 'vacation',
  'vacation': 'vacation',
  'laptop': 'electronics',
  'computer': 'electronics',
  'camera': 'electronics',
  'software': 'electronics',
  'app': 'electronics',
  'cleaning': 'services',
  'repair': 'services',
  'laundry': 'services',
  'mechanic': 'services',
  'plumber': 'services',
  'electrician': 'services',
  'haircut': 'personal',
  'salon': 'personal',
  'spa': 'personal',
  'makeup': 'personal',
  'massage': 'personal',
  'cosmetics': 'personal',
  'salary': 'income',
  'paycheck': 'income',
  'wages': 'income',
  'bonus': 'income',
  'deposit': 'income',
  'payroll': 'work',
  'client': 'freelance',
  'project': 'freelance',
  'contract': 'freelance',
  'sales': 'business',
  'revenue': 'business',
  'profit': 'business',
  'misc': 'other',
  'general': 'other',
  'stuff': 'other',
  'unknown': 'other',
  'atm': 'bills', 
  'cash': 'bills', 
  'withdrawal': 'bills',
  'fee': 'bills',
};

export const SMART_CATEGORIES_ES: Record<string, string> = {
  ...SHARED_CATEGORIES,
  'gasolina': 'transport',
  'combustible': 'transport',
  'peaje': 'transport',
  'estacionamiento': 'transport',
  'metro': 'transport',
  'colectivo': 'transport',
  'autobus': 'transport',
  'tren': 'transport',
  'cafeteria': 'coffee',
  'cafe': 'coffee',
  'suscripcion': 'subscription',
  'cine': 'entertainment',
  'juego': 'entertainment',
  'videojuego': 'entertainment',
  'concierto': 'entertainment',
  'pelicula': 'entertainment',
  'entradas': 'entertainment',
  'museo': 'entertainment',
  'parque': 'entertainment',
  'discoteca': 'entertainment',
  'gimnasio': 'health',
  'medico': 'health',
  'farmacia': 'health',
  'medicamento': 'health',
  'salud': 'health',
  'consulta': 'health',
  'dentista': 'health',
  'lentes': 'health',
  'mercado': 'food',
  'supermercado': 'food',
  'cena': 'food',
  'almuerzo': 'food',
  'restaurante': 'food',
  'compra': 'food',
  'hamburguesa': 'food',
  'desayuno': 'food',
  'panaderia': 'food',
  'merienda': 'food',
  'bebidas': 'food',
  'comida': 'food',
  'ropa': 'shopping',
  'zapatos': 'shopping',
  'curso': 'education',
  'matricula': 'education',
  'mensualidad': 'education',
  'libro': 'education',
  'escuela': 'education',
  'universidad': 'education',
  'clase': 'education',
  'alquiler': 'home',
  'arenta': 'home',
  'hipoteca': 'home',
  'casa': 'home',
  'electricidad': 'bills',
  'luz': 'bills',
  'agua': 'bills',
  'telefono': 'bills',
  'celular': 'bills',
  'efectivo': 'bills',
  'retiro': 'bills',
  'comision': 'bills',
  'vuelo': 'travel',
  'boleto': 'travel',
  'viaje': 'travel',
  'hotel': 'travel',
  'cumpleanos': 'gift',
  'regalo': 'gift',
  'donacion': 'charity',
  'ong': 'charity',
  'iglesia': 'charity',
  'diezmo': 'charity',
  'acciones': 'investment',
  'cripto': 'investment',
  'ahorro': 'investment',
  'inversion': 'investment',
  'veterinario': 'pets',
  'perro': 'pets',
  'gato': 'pets',
  'mascota': 'pets',
  'bebe': 'kids',
  'panales': 'kids',
  'guarderia': 'kids',
  'juguetes': 'kids',
  'ninos': 'kids',
  'seguro': 'insurance',
  'poliza': 'insurance',
  'impuesto': 'taxes',
  'seniat': 'taxes',
  'auditoria': 'taxes',
  'islr': 'taxes',
  'playa': 'vacation',
  'vacaciones': 'vacation',
  'computadora': 'electronics',
  'camara': 'electronics',
  'aplicacion': 'electronics',
  'limpieza': 'services',
  'reparacion': 'services',
  'lavanderia': 'services',
  'mecanico': 'services',
  'plomero': 'services',
  'electricista': 'services',
  'corte': 'personal',
  'peluqueria': 'personal',
  'salon': 'personal',
  'maquillaje': 'personal',
  'masaje': 'personal',
  'cosmeticos': 'personal',
  'salario': 'income',
  'sueldo': 'income',
  'bono': 'income',
  'deposito': 'income',
  'nomina': 'work',
  'cliente': 'freelance',
  'proyecto': 'freelance',
  'contrato': 'freelance',
  'ventas': 'business',
  'ingresos': 'business',
  'ganancia': 'business',
  'otros': 'other',
  'varios': 'other',
};

export const SMART_CATEGORIES_PT: Record<string, string> = {
  ...SHARED_CATEGORIES,
  'gasolina': 'transport',
  'combustivel': 'transport',
  'pedagio': 'transport',
  'estacionamento': 'transport',
  'metro': 'transport',
  'onibus': 'transport',
  'trem': 'transport',
  'cafeteria': 'coffee',
  'cafe': 'coffee',
  'assinatura': 'subscription',
  'jogo': 'entertainment',
  'videogame': 'entertainment',
  'show': 'entertainment',
  'filme': 'entertainment',
  'ingressos': 'entertainment',
  'museu': 'entertainment',
  'parque': 'entertainment',
  'balada': 'entertainment',
  'academia': 'health',
  'medico': 'health',
  'farmacia': 'health',
  'remedio': 'health',
  'saude': 'health',
  'consulta': 'health',
  'dentista': 'health',
  'oculos': 'health',
  'mercado': 'food',
  'supermercado': 'food',
  'jantar': 'food',
  'almoco': 'food',
  'restaurante': 'food',
  'compras': 'food',
  'hamburguer': 'food',
  'cafe da manha': 'food',
  'padaria': 'food',
  'lanche': 'food',
  'bebidas': 'food',
  'comida': 'food',
  'roupas': 'shopping',
  'sapatos': 'shopping',
  'curso': 'education',
  'matricula': 'education',
  'mensalidade': 'education',
  'livro': 'education',
  'escola': 'education',
  'universidade': 'education',
  'aula': 'education',
  'aluguel': 'home',
  'hipoteca': 'home',
  'casa': 'home',
  'eletricidade': 'bills',
  'luz': 'bills',
  'agua': 'bills',
  'telefone': 'bills',
  'celular': 'bills',
  'dinheiro': 'bills',
  'saque': 'bills',
  'taxa': 'bills',
  'voo': 'travel',
  'passagem': 'travel',
  'viagem': 'travel',
  'hotel': 'travel',
  'aniversario': 'gift',
  'presente': 'gift',
  'doacao': 'charity',
  'ong': 'charity',
  'igreja': 'charity',
  'dizimo': 'charity',
  'acoes': 'investment',
  'cripto': 'investment',
  'poupanca': 'investment',
  'investimento': 'investment',
  'veterinario': 'pets',
  'cachorro': 'pets',
  'gato': 'pets',
  'pet': 'pets',
  'bebe': 'kids',
  'fraldas': 'kids',
  'creche': 'kids',
  'brinquedos': 'kids',
  'criancas': 'kids',
  'seguro': 'insurance',
  'apolice': 'insurance',
  'imposto': 'taxes',
  'auditoria': 'taxes',
  'praia': 'vacation',
  'ferias': 'vacation',
  'computador': 'electronics',
  'aplicativo': 'electronics',
  'limpeza': 'services',
  'reparo': 'services',
  'lavanderia': 'services',
  'mecanico': 'services',
  'encanador': 'services',
  'eletricista': 'services',
  'corte': 'personal',
  'barbearia': 'personal',
  'cabeleireiro': 'personal',
  'salao': 'personal',
  'maquiagem': 'personal',
  'massagem': 'personal',
  'cosmeticos': 'personal',
  'salario': 'income',
  'bonus': 'income',
  'bônus': 'income',
  'deposito': 'income',
  'folha': 'work',
  'folha de pagamento': 'work',
  'cliente': 'freelance',
  'projeto': 'freelance',
  'contrato': 'freelance',
  'vendas': 'business',
  'receita': 'business',
  'lucro': 'business',
  'outros': 'other',
  'varios': 'other',
};

export const getSmartCategories = (lang: string) => {
  if (lang === 'es') return SMART_CATEGORIES_ES;
  if (lang === 'pt') return SMART_CATEGORIES_PT;
  return SMART_CATEGORIES_EN;
};